services:
  db:
    image: postgres:15-alpine
    container_name: tickets_postgres
    restart: always
    environment:
      POSTGRES_USER: morvibus
      POSTGRES_PASSWORD: TuPasswordSegura2026
      POSTGRES_DB: tickets_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tickets_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U morvibus -d tickets_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: tickets_fastapi
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    environment:
      - DATABASE_URL=postgresql://morvibus:TuPasswordSegura2026@db:5432/tickets_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tickets_net

volumes:
  postgres_data:
  uploads_data:

networks:
  tickets_net:
    driver: bridge
